"""
Computer Vision Integrity Assurance Framework (CVIF)
Trustworthy Computer Vision Integrity Assurance for Data, Models, and Inference Outputs.
Ministry of Defence (MoD) / Indian Army (DGIS)
"""

from cvif.version import __version__, __schema_version__
from cvif.core import (
    AssetStatus,
    AssetType,
    AuditEventType,
    Disposition,
    EvidenceType,
    KeyStatus,
    KeyType,
    ModelAccessLevel,
    ModelTask,
    ProvenanceOutcome,
    RecordOrigin,
    SessionStatus,
    SeverityLevel,
    CVIFError,
    CVIFValidationError,
    CVIFStorageError,
    CVIFCryptographicError,
    CVIFAuditChainError,
    CVIFProvenanceError,
    CVIFCorruptedArtifactError,
    CVIFInvalidModelError,
    CVIFConfigurationError,
    AnalysisSession,
    ArtifactReference,
    AssetFileManifestEntry,
    AssetRegistration,
    AssuranceVerdict,
    AuditEvent,
    ClassificationOutput,
    DetectionOutput,
    EvidenceRecord,
    Finding,
    HashManifest,
    InferenceRecord,
    ProvenanceVerificationResult,
    KeyRecord,
    PredictionResult,
    SegmentationOutput,
    ShiftAssessment,
    ShiftDimensionResult,
    ShiftReport,
    ValidationResult,
    UnifiedDataset,
    ImageRecord,
    AnnotationRecord,
    ClassInfo,
    CVIFConfig,
    load_config,
)

__all__ = [
    "__version__",
    "__schema_version__",
    # Enums
    "AssetStatus",
    "AssetType",
    "AuditEventType",
    "Disposition",
    "EvidenceType",
    "KeyStatus",
    "KeyType",
    "ModelAccessLevel",
    "ModelTask",
    "ProvenanceOutcome",
    "RecordOrigin",
    "SessionStatus",
    "SeverityLevel",
    # Exceptions
    "CVIFError",
    "CVIFValidationError",
    "CVIFStorageError",
    "CVIFCryptographicError",
    "CVIFAuditChainError",
    "CVIFProvenanceError",
    "CVIFCorruptedArtifactError",
    "CVIFInvalidModelError",
    "CVIFConfigurationError",
    # Schemas
    "AnalysisSession",
    "ArtifactReference",
    "AssetFileManifestEntry",
    "AssetRegistration",
    "AssuranceVerdict",
    "AuditEvent",
    "ClassificationOutput",
    "DetectionOutput",
    "EvidenceRecord",
    "Finding",
    "HashManifest",
    "InferenceRecord",
    "ProvenanceVerificationResult",
    "KeyRecord",
    "PredictionResult",
    "SegmentationOutput",
    "ShiftAssessment",
    "ShiftDimensionResult",
    "ShiftReport",
    "ValidationResult",
    "UnifiedDataset",
    "ImageRecord",
    "AnnotationRecord",
    "ClassInfo",
    # Config
    "CVIFConfig",
    "load_config",
]
