"""CVIF Command-Line Interface package (Phase 9)."""

from cvif.cli.exit_codes import (
    EXIT_ASSURANCE_QUARANTINE,
    EXIT_ASSURANCE_REVIEW,
    EXIT_CLI_ERROR,
    EXIT_CONFIG_ERROR,
    EXIT_DATA_INTEGRITY_FINDING,
    EXIT_INTERNAL_ERROR,
    EXIT_MODEL_INTEGRITY_FINDING,
    EXIT_NOT_FOUND,
    EXIT_PROVENANCE_FAILED,
    EXIT_SHIFT_DETECTED,
    EXIT_SUCCESS,
    EXIT_TAMPER_DETECTED,
    EXIT_UNSUPPORTED,
    EXIT_VALIDATION_ERROR,
)
from cvif.cli.main import app, run_cli

__all__ = [
    "app",
    "run_cli",
    "EXIT_SUCCESS",
    "EXIT_CLI_ERROR",
    "EXIT_CONFIG_ERROR",
    "EXIT_VALIDATION_ERROR",
    "EXIT_ASSURANCE_REVIEW",
    "EXIT_ASSURANCE_QUARANTINE",
    "EXIT_DATA_INTEGRITY_FINDING",
    "EXIT_MODEL_INTEGRITY_FINDING",
    "EXIT_PROVENANCE_FAILED",
    "EXIT_SHIFT_DETECTED",
    "EXIT_TAMPER_DETECTED",
    "EXIT_NOT_FOUND",
    "EXIT_UNSUPPORTED",
    "EXIT_INTERNAL_ERROR",
]
