"""Core enumeration types for the CVIF architecture."""

from enum import Enum


class AssetType(str, Enum):
    DATASET = "DATASET"
    MODEL = "MODEL"
    INFERENCE_RECORD = "INFERENCE_RECORD"


class AssetStatus(str, Enum):
    REGISTERED = "REGISTERED"
    ANALYSING = "ANALYSING"
    ANALYSED = "ANALYSED"
    QUARANTINED = "QUARANTINED"


class SeverityLevel(str, Enum):
    INFORMATIONAL = "INFORMATIONAL"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class Disposition(str, Enum):
    ACCEPT = "ACCEPT"
    REVIEW = "REVIEW"
    QUARANTINE = "QUARANTINE"


class EvidenceType(str, Enum):
    STATISTICAL = "STATISTICAL"
    VISUAL = "VISUAL"
    CRYPTOGRAPHIC = "CRYPTOGRAPHIC"
    BEHAVIORAL = "BEHAVIORAL"
    COMPARATIVE = "COMPARATIVE"


class ModelAccessLevel(str, Enum):
    WHITE_BOX = "WHITE_BOX"
    GREY_BOX = "GREY_BOX"
    BLACK_BOX = "BLACK_BOX"


class ModelTask(str, Enum):
    CLASSIFICATION = "CLASSIFICATION"
    DETECTION = "DETECTION"
    SEGMENTATION = "SEGMENTATION"
    UNKNOWN = "UNKNOWN"


class BatteryDifficulty(str, Enum):
    EASY = "EASY"
    MEDIUM = "MEDIUM"
    HARD = "HARD"


class RecordOrigin(str, Enum):
    INTERNAL = "INTERNAL"
    EXTERNAL = "EXTERNAL"


class KeyType(str, Enum):
    ED25519_PUBLIC = "ED25519_PUBLIC"
    ED25519_PRIVATE = "ED25519_PRIVATE"
    HMAC_SECRET = "HMAC_SECRET"


class KeyStatus(str, Enum):
    ACTIVE = "ACTIVE"
    SUSPENDED = "SUSPENDED"
    REVOKED = "REVOKED"
    EXPIRED = "EXPIRED"


class AuditEventType(str, Enum):
    ASSET_INGESTED = "ASSET_INGESTED"
    ANALYSIS_STARTED = "ANALYSIS_STARTED"
    ANALYSIS_COMPLETED = "ANALYSIS_COMPLETED"
    FINDING_RECORDED = "FINDING_RECORDED"
    VERDICT_ISSUED = "VERDICT_ISSUED"
    DISPOSITION_APPLIED = "DISPOSITION_APPLIED"
    CHAIN_VERIFIED = "CHAIN_VERIFIED"
    CONFIG_CHANGED = "CONFIG_CHANGED"
    SYSTEM_STARTED = "SYSTEM_STARTED"
    KEY_IMPORTED = "KEY_IMPORTED"
    KEY_REVOKED = "KEY_REVOKED"
    EVIDENCE_STORED = "EVIDENCE_STORED"
    ARTIFACT_STORED = "ARTIFACT_STORED"
    EVIDENCE_VERIFIED = "EVIDENCE_VERIFIED"
    EVIDENCE_TAMPERED = "EVIDENCE_TAMPERED"


class SessionStatus(str, Enum):
    INITIALIZING = "INITIALIZING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    DEGRADED = "DEGRADED"


class ProvenanceOutcome(str, Enum):
    VERIFIED = "VERIFIED"
    VERIFIED_WITH_WARNING = "VERIFIED_WITH_WARNING"
    UNVERIFIED_KEY = "UNVERIFIED_KEY"
    TAMPERED_OUTPUT = "TAMPERED_OUTPUT"
    SUBSTITUTED_MODEL = "SUBSTITUTED_MODEL"
    REPLAYED_RECORD = "REPLAYED_RECORD"
    EXPIRED_KEY = "EXPIRED_KEY"
    UNSUPPORTED = "UNSUPPORTED"

